buttonSkinSharkPlannerAmber = 'button_SharkPlanner_amber.skin.lua'
buttonSkinSharkPlannerGreen = 'button_SharkPlanner_green.skin.lua'
toggleSkinSharkPlannerAmber = 'toggle_SharkPlanner_amber.skin.lua'
toggleSkinSharkPlannerGreen = 'toggle_SharkPlanner_green.skin.lua'
toggleSkinSharkPlannerLongAmber = 'toggle_SharkPlanner_long_amber.skin.lua'
toggleSkinSharkPlannerLongGreen = 'toggle_SharkPlanner_long_green.skin.lua'